/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BL;
import BL.User;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dominik
 */
public class GUI extends javax.swing.JFrame {

    private BL bl = new BL();
    private String text;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        liUser.setModel(bl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmUser = new javax.swing.JPopupMenu();
        miCreateUser = new javax.swing.JMenuItem();
        miDeleteUser = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        liUser = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        btEnterText = new javax.swing.JButton();
        btAnalyze = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btLoadFromFile = new javax.swing.JButton();

        pmUser.setComponentPopupMenu(pmUser);

        miCreateUser.setText("Create User");
        miCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateUserActionPerformed(evt);
            }
        });
        pmUser.add(miCreateUser);

        miDeleteUser.setText("Delete User");
        miDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteUserActionPerformed(evt);
            }
        });
        pmUser.add(miDeleteUser);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        liUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        liUser.setComponentPopupMenu(pmUser);
        jScrollPane1.setViewportView(liUser);

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane2.setViewportView(taOutput);

        btEnterText.setText("Enter Text");
        btEnterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnterTextActionPerformed(evt);
            }
        });

        btAnalyze.setText("Analyze");
        btAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalyzeActionPerformed(evt);
            }
        });

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btLoadFromFile.setText("Load");
        btLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadFromFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEnterText, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAnalyze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLoadFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnterText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to create a User in the GUI
     * 
     * Gets a User from the User class
     * 
     * @param evt 
     */
    private void miCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateUserActionPerformed
       String name = JOptionPane.showInputDialog(null, "Please enter name: ");
       User u = new User(name);
       bl.addUsers(u);
    }//GEN-LAST:event_miCreateUserActionPerformed

    /**
     * Method to delete a User
     * 
     * Gets the index and deletes the User at this position
     * 
     * @param evt 
     */
    private void miDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteUserActionPerformed
        int i = liUser.getSelectedIndex();
        bl.delete(i);
    }//GEN-LAST:event_miDeleteUserActionPerformed

    private void btEnterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnterTextActionPerformed
        if(!liUser.isSelectionEmpty()){    
            EnterTextGUI dialog = new EnterTextGUI(this, true);
            dialog.setVisible(true);

            if(dialog.isOk()){
                text = dialog.getText();
            }
        } else{
            JOptionPane.showMessageDialog(this, "Please select a User");
        }
    }//GEN-LAST:event_btEnterTextActionPerformed

    private void btAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalyzeActionPerformed
        if(!liUser.isSelectionEmpty()){
            try {
                User u = bl.getElementAt(liUser.getSelectedIndex());
                taOutput.append(u.getName()+"\n");
                
                bl.addResults(new File("D:\\Schulordner\\POS Stuff\\Project_Personality-Traits\\profile.json"), u, text);
                
                Iterator it = u.getTraits().entrySet().iterator();
                while (it.hasNext()) {
                    Map.Entry pair = (Map.Entry)it.next();
                    taOutput.append(pair.getKey() + " = " + pair.getValue()+"\n");
                }
                taOutput.append("\n");
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btAnalyzeActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        try {
            bl.save(new File("D:\\Schulordner\\POS Stuff\\Project_Personality-Traits\\results.ser"), taOutput.getText());
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadFromFileActionPerformed
        try {
            bl.loadFromFile(new File("D:\\Schulordner\\POS Stuff\\Project_Personality-Traits\\results.ser"));
            refresh();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLoadFromFileActionPerformed

    private void refresh(){
        for (int i = 0; i < bl.getSize(); i++) {
            User u = bl.getElementAt(i);           
            if(u.getTraits() != null){
                taOutput.append(u.getName()+"\n");
                Iterator it = u.getTraits().entrySet().iterator();
                    while (it.hasNext()) {
                    Map.Entry pair = (Map.Entry)it.next();
                    taOutput.append(pair.getKey() + " = " + pair.getValue()+"\n");
                }
                taOutput.append("\n");
            }
        }
    }
    
    private static BigDecimal truncateDecimal(double x,int numberofDecimals)
    {
        if ( x > 0) {
            return new BigDecimal(String.valueOf(x)).setScale(numberofDecimals, BigDecimal.ROUND_FLOOR);
        } else {
            return new BigDecimal(String.valueOf(x)).setScale(numberofDecimals, BigDecimal.ROUND_CEILING);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnalyze;
    private javax.swing.JButton btEnterText;
    private javax.swing.JButton btLoadFromFile;
    private javax.swing.JButton btSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> liUser;
    private javax.swing.JMenuItem miCreateUser;
    private javax.swing.JMenuItem miDeleteUser;
    private javax.swing.JPopupMenu pmUser;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
